; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.4.1 on Mon Sep 30 2024 11:07:36 GMT+0200 (Central European Summer Time)

